spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data_jpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接数量
      minimum-idle: 2
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 4
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 10
#      min-idle: 10
#      max-active: 30
#      name: test-121