spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data_jpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
